export const announcementData = [
    {
        id: 1,
        image: "#",
        date: "25/6/2024",
        title: "AI in modern business environment",
        subtitle: "Higher School Students considering Business Careers",
        mode: "In person",
        ctaText: "Click to Register",
        type: "event",
    },
    {
        id: 2,
        image: "#",
        date: "25/6/2024",
        title: "AI in modern business environment",
        subtitle: "Higher School Students considering Business Careers",
        mode: "Hybrid",
        ctaText: "Click to Register",
        type: "event",
    },
    {
        id: 3,
        image: "#",
        date: "25/6/2024",
        title: "AI in modern business environment",
        subtitle: "Higher School Students considering Business Careers",
        mode: "Online",
        ctaText: "Click to Register",
        type: "event",
    },
    {
        id: 4,
        image: "#",
        date: "25/6/2024",
        title: "Scholarship Announcement",
        subtitle: "Higher School Students considering Business Careers",
        badgeText: "50% Scholarship",
        ctaText: "Tell me more",
        type: "announcement",
    },
    {
        id: 5,
        image: "#",
        date: "10/7/2024",
        title: "Careers in Data Science",
        subtitle: "Undergraduate Students & Freshers",
        mode: "Online",
        ctaText: "Click to Register",
        type: "event",
    },
    {
        id: 6,
        image: "#",
        date: "15/7/2024",
        title: "Future of Engineering Education",
        subtitle: "Students exploring STEM careers",
        mode: "In person",
        ctaText: "Click to Register",
        type: "event",
    },
    {
        id: 7,
        image: "#",
        date: "20/7/2024",
        title: "Study Abroad Webinar",
        subtitle: "Students planning international education",
        mode: "Online",
        ctaText: "Click to Register",
        type: "event",
    },
    {
        id: 8,
        image: "#",
        date: "30/7/2024",
        title: "University Medical School Announcement",
        subtitle: "Outstanding students from India",
        badgeText: "New Scholarships Available",
        ctaText: "Tell me more",
        type: "announcement",
    },
];
